pipeline {
    agent {
        dockerfile {
            dir '.ci'
            label 'docker-executor'
        }
    }

    options {
        withAWS(
            endpointUrl: 'https://storage.kevinlin.info',
            credentials: 'storage-internal',
        )
    }

    stages {
        stage('Environment') {
            steps {
                s3Download(
                    bucket: 'internal',
                    path: 'resources/dotproxy/config.yaml',
                    file: 'config.yaml',
                )
            }
        }
        stage('Install') {
            steps {
                sh 'go get -d ./...'
            }
        }
        stage('Lint') {
            steps {
               sh 'make lint'
            }
        }
        stage('Build') {
            environment {
                VERSION_SHA = "${GIT_COMMIT}"
            }
            parallel {
                stage('linux/386') {
                    environment {
                        GOOS = 'linux'
                        GOARCH = '386'
                    }
                    steps {
                        sh 'make'
                    }
                }
                stage('linux/amd64') {
                    environment {
                        GOOS = 'linux'
                        GOARCH = 'amd64'
                    }
                    steps {
                        sh 'make'
                    }
                }
                stage('linux/arm') {
                    environment {
                        GOOS = 'linux'
                        GOARCH = 'arm'
                    }
                    steps {
                        sh 'make'
                    }
                }
                stage('linux/arm64') {
                    environment {
                        GOOS = 'linux'
                        GOARCH = 'arm64'
                    }
                    steps {
                        sh 'make'
                    }
                }
            }
        }
        stage('Release') {
            steps {
                sh 'tar -cvzf release.tar.gz bin/ init/ config.yaml'
                s3Upload(
                    bucket: 'internal',
                    path: "deploy/${env.JOB_NAME}/${env.GIT_COMMIT}/",
                    file: 'release.tar.gz',
                )
            }
        }
        stage('Deploy') {
            environment {
                DOMAIN = 'dotproxy.static.kevinlin.info'
                GITHUB_REMOTE = 'git@github.com:LINKIWI/dotproxy.git'
            }
            steps {
                // Switch to the static branch with a clean working directory
                sh 'git rm -rf .'
                sh 'git clean -fxd'
                sh 'git fetch --all'
                sh 'git checkout -f static'
                sh 'git reset --hard origin/static'

                // Download release archive
                s3Download(
                    bucket: 'internal',
                    path: "deploy/${env.JOB_NAME}/${env.GIT_COMMIT}/release.tar.gz",
                    file: 'release.tar.gz',
                )
                sh 'tar xvf release.tar.gz'
                sh 'rm release.tar.gz'

                // Create release directory
                sh "mkdir -p releases/${GIT_COMMIT}/"
                sh "ln -sTfv ${GIT_COMMIT} releases/latest"
                sh "mv bin/* releases/${GIT_COMMIT}/"
                sh 'git add releases/'
                sh 'git clean -fxd'

                // Generate page index
                sh "echo ${DOMAIN} > CNAME"
                sh 'apindex . .git,CNAME'

                // Commit and push
                sh 'git add -A'
                sh "git commit --no-verify -m \"[automatic commit] ${GIT_BRANCH}:${GIT_COMMIT}\" || :"
                sh "git remote add github ${GITHUB_REMOTE}"
                sh 'git push origin HEAD'
                sh 'git push github HEAD:gh-pages'
            }
        }
    }
}
